name: Update Requirements

on:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.8  # Any default version for running the script

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pru

      - name: Run requirements updater script
        run: |
          bash .github/scripts/update_requirements.sh
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
